name: ASPIRE Python Pip CI

on:
  push:
  

jobs:
  conda-build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        backend: [default]
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Conda ${{ matrix.os }} Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: aspire
        environment-file: environment-${{ matrix.backend }}.yml
        auto-activate-base: false
    - name: Complete Install and Log Environment ${{ matrix.os }} Python ${{ matrix.python-version }}
      run: |
        conda info
        conda list
        #if [[ "${{ matrix.os }}" == "windows-2019" ]]
        #then
        #  pip install -f https://files.pythonhosted.org/packages/a8/37/04143aee63e3773debe77979e44f85e1e22d87c1948f5acab4cca3d1ecee/finufft-2.2.0-py3-none-win_amd64.whl --no-index finufft
        #fi
        pip install -e ".[dev]"
        pip freeze
        python -c "import numpy; numpy.show_config()"
    - name: Execute Pytest Conda ${{ matrix.os }} Python ${{ matrix.python-version }}
      run: |
        export OMP_NUM_THREADS=2
        # -n runs test in parallel using pytest-xdist
        pytest -rP tests/test_utils.py


