name: ASPIRE Python Pip CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:


jobs:
  conda-build:
    runs-on: ${{ matrix.os }}
    # Only run on review ready pull_requests
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        backend: [default]
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Conda ${{ matrix.os }} Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2.3.0
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: aspire
        environment-file: environment-${{ matrix.backend }}.yml
        auto-activate-base: false
    - name: Complete Install and Log Environment ${{ matrix.os }} Python ${{ matrix.python-version }}
      run: |
        conda info
        conda list
        pip install -e ".[dev]"
        pip freeze
        python -c "import numpy; numpy.show_config()"
    - name: Execute Pytest Conda ${{ matrix.os }} Python ${{ matrix.python-version }}
      run: |
        export OMP_NUM_THREADS=2
        # -n runs test in parallel using pytest-xdist
        pytest -s tests/test_mean_estimator_boosting.py tests/test_utils.py
    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
